Repository jakubkulhan/bunny, pull requests merged in 2025-03, with the labels that each got.

#167 Better typehints
  phpcs.xml
  phpstan.neon
  spec/generate.php
  src/ChannelInterface.php
  src/ChannelMethods.php
  src/Connection.php
Labels: enhancement

#170 [0.6.x] Await for connection in async
  src/Client.php
  test/ClientTest.php
Labels: bug, enhancement

#172 [0.6.x] One command local testing
  Makefile
  docker-compose.yml
Labels: enhancement

#173 [0.6.x] Strengthen channel consume test assertations
  test/ChannelTest.php
Labels: bug
